// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProsessPortal.Infrastructure.Data;

#nullable disable

namespace ProsessPortal.Infrastructure.Migrations
{
    [DbContext(typeof(ProsessPortalDbContext))]
    [Migration("20251126200749_AddActorExtensions")]
    partial class AddActorExtensions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProsessPortal.Core.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorCategory")
                        .HasColumnType("integer");

                    b.Property<int>("ActorType")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CommandStructure")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ContractNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ContractStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("EmployeeCount")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GeographicLocation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ManagerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ManagerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrganizationName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParentOrganization")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("PersonnelCount")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SecurityClearance")
                        .HasColumnType("integer");

                    b.Property<string>("UnitCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UnitMission")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UnitName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UnitType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("VendorId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ActorCategory");

                    b.HasIndex("ActorType");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationName");

                    b.HasIndex("SecurityClearance");

                    b.HasIndex("UnitName");

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActorCategory = 0,
                            ActorType = 0,
                            CreatedAt = new DateTime(2025, 9, 24, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Department = "IT-avdelingen",
                            Email = "lars.johansen@forsvaret.no",
                            FirstName = "Lars",
                            GeographicLocation = "Oslo",
                            IsActive = true,
                            LastName = "Johansen",
                            OrganizationName = "Forsvaret",
                            Phone = "+47 98765432",
                            Position = "IT-arkitekt",
                            PreferredLanguage = "NO",
                            SecurityClearance = 3
                        },
                        new
                        {
                            Id = 2,
                            ActorCategory = 0,
                            ActorType = 4,
                            ContractEndDate = new DateTime(2026, 8, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            ContractNumber = "K-2025-001",
                            ContractStartDate = new DateTime(2025, 8, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 8, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Department = "Support",
                            Email = "john.smith@techcorp.com",
                            FirstName = "John",
                            GeographicLocation = "Oslo",
                            IsActive = true,
                            LastName = "Smith",
                            OrganizationName = "TechCorp AS",
                            Phone = "+47 76543210",
                            Position = "Senior konsulent",
                            PreferredLanguage = "EN",
                            SecurityClearance = 1,
                            VendorId = "TECH001"
                        },
                        new
                        {
                            Id = 3,
                            ActorCategory = 1,
                            ActorType = 4,
                            Address = "Teknologigaten 15, 0150 Oslo",
                            ContractEndDate = new DateTime(2026, 8, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            ContractNumber = "K-2025-001",
                            ContractStartDate = new DateTime(2025, 8, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 8, 25, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Department = "IT Services",
                            Email = "contact@techcorp.com",
                            EmployeeCount = 150,
                            GeographicLocation = "Oslo",
                            IsActive = true,
                            OrganizationName = "TechCorp AS",
                            ParentOrganization = "TechCorp International",
                            Phone = "+47 22 12 34 56",
                            PreferredLanguage = "NO",
                            RegistrationNumber = "987654321",
                            SecurityClearance = 1,
                            VendorId = "TECH001"
                        },
                        new
                        {
                            Id = 4,
                            ActorCategory = 2,
                            ActorType = 0,
                            CommandStructure = "Hærstaben",
                            CreatedAt = new DateTime(2025, 7, 26, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Email = "cyb.bde@forsvaret.no",
                            GeographicLocation = "Lillehammer",
                            IsActive = true,
                            OrganizationName = "Forsvaret",
                            PersonnelCount = 1200,
                            Phone = "+47 23 09 50 00",
                            PreferredLanguage = "NO",
                            SecurityClearance = 3,
                            UnitCode = "CYB-BDE",
                            UnitMission = "Ansvarlig for cyberoperasjoner og digitalt forsvar",
                            UnitName = "Cyber Brigade",
                            UnitType = "Brigade"
                        },
                        new
                        {
                            Id = 5,
                            ActorCategory = 2,
                            ActorType = 0,
                            CommandStructure = "Brigade Nord",
                            CreatedAt = new DateTime(2025, 8, 15, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Department = "Brigade Nord",
                            Email = "2btn@forsvaret.no",
                            GeographicLocation = "Setermoen",
                            IsActive = true,
                            OrganizationName = "Forsvaret",
                            PersonnelCount = 600,
                            Phone = "+47 75 50 30 00",
                            PreferredLanguage = "NO",
                            SecurityClearance = 2,
                            UnitCode = "2-BTN",
                            UnitMission = "Stridsklare styrker for forsvar av Nord-Norge",
                            UnitName = "2. Bataljon",
                            UnitType = "Bataljon"
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ActorNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("ActorNotes");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ActorRole", b =>
                {
                    b.Property<int>("ActorId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ActorId", "RoleId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("IsActive");

                    b.HasIndex("RoleId");

                    b.ToTable("ActorRoles");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Resource", "Action")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "view",
                            Description = "Se prosesser",
                            Name = "view_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 2,
                            Action = "create",
                            Description = "Opprette prosesser",
                            Name = "create_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 3,
                            Action = "edit",
                            Description = "Redigere prosesser",
                            Name = "edit_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 4,
                            Action = "delete",
                            Description = "Slette prosesser",
                            Name = "delete_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 5,
                            Action = "approve",
                            Description = "Godkjenne prosesser",
                            Name = "approve_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 6,
                            Action = "view",
                            Description = "Se QA-kø",
                            Name = "view_qa_queue",
                            Resource = "qa"
                        },
                        new
                        {
                            Id = 7,
                            Action = "approve",
                            Description = "Godkjenne endringer",
                            Name = "approve_changes",
                            Resource = "qa"
                        },
                        new
                        {
                            Id = 8,
                            Action = "reject",
                            Description = "Avvise endringer",
                            Name = "reject_changes",
                            Resource = "qa"
                        },
                        new
                        {
                            Id = 9,
                            Action = "manage",
                            Description = "Administrere brukere",
                            Name = "manage_users",
                            Resource = "user"
                        },
                        new
                        {
                            Id = 10,
                            Action = "manage",
                            Description = "Administrere roller",
                            Name = "manage_roles",
                            Resource = "role"
                        },
                        new
                        {
                            Id = 11,
                            Action = "view",
                            Description = "Se audit-logg",
                            Name = "view_audit_log",
                            Resource = "audit"
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Prosess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DeletedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GitPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GitRepository")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DeletedByUserId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.ToTable("Prosesser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "HR",
                            CreatedAt = new DateTime(2025, 10, 24, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Komplett prosess for å ta imot nye medarbeidere",
                            GitBranch = "main",
                            IsActive = true,
                            IsDeleted = false,
                            Status = 5,
                            Title = "Ny medarbeider onboarding",
                            UpdatedAt = new DateTime(2025, 11, 18, 17, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 25
                        },
                        new
                        {
                            Id = 2,
                            Category = "IT",
                            CreatedAt = new DateTime(2025, 10, 9, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Prosess for bestilling av nytt IT-utstyr til medarbeidere",
                            GitBranch = "main",
                            IsActive = true,
                            IsDeleted = false,
                            Status = 5,
                            Title = "IT-utstyr bestilling",
                            UpdatedAt = new DateTime(2025, 11, 13, 17, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 18
                        },
                        new
                        {
                            Id = 3,
                            Category = "Økonomi",
                            CreatedAt = new DateTime(2025, 11, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Standard prosess for håndtering og godkjenning av fakturaer",
                            GitBranch = "main",
                            IsActive = true,
                            IsDeleted = false,
                            Status = 5,
                            Title = "Fakturahåndtering",
                            UpdatedAt = new DateTime(2025, 11, 21, 17, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 42
                        },
                        new
                        {
                            Id = 4,
                            Category = "Kundeservice",
                            CreatedAt = new DateTime(2025, 11, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Håndtering av kundehenvendelser i support-system",
                            GitBranch = "main",
                            IsActive = true,
                            IsDeleted = false,
                            Status = 2,
                            Title = "Kundehenvendelser support",
                            UpdatedAt = new DateTime(2025, 11, 22, 17, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 8
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessApprovalComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalRequestId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("ProsessApprovalComments");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessApprovalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FromStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<int>("ToStatus")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ProsessId");

                    b.HasIndex("UserId");

                    b.ToTable("ProsessApprovalHistory");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RequestComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RequestedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("ProsessId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("ProsessApprovalRequests");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessAutoSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("character varying(20000)");

                    b.Property<bool>("IsRestored")
                        .HasColumnType("boolean");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProsessId");

                    b.HasIndex("SavedAt");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("ProsessAutoSaves");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessDeletionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActionAt");

                    b.HasIndex("ProsessId");

                    b.HasIndex("UserId");

                    b.ToTable("ProsessDeletionHistory");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessEditConflict", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConflictingFields")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<int?>("Resolution")
                        .HasColumnType("integer");

                    b.Property<string>("ResolutionComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ResolvedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SessionId2")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("UserId1")
                        .HasColumnType("integer");

                    b.Property<int>("UserId2")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt");

                    b.HasIndex("ProsessId");

                    b.HasIndex("ResolvedByUserId");

                    b.HasIndex("UserId1");

                    b.HasIndex("UserId2");

                    b.ToTable("ProsessEditConflicts");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessEditSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CompletionComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("CreatedVersionId")
                        .HasColumnType("integer");

                    b.Property<string>("DraftCategory")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DraftDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DraftSteps")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)");

                    b.Property<string>("DraftTags")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DraftTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastActivity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastAutoSave")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StartComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedVersionId");

                    b.HasIndex("LastActivity");

                    b.HasIndex("ProsessId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("ProsessEditSessions");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DetailedInstructions")
                        .HasColumnType("text");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentStepId")
                        .HasColumnType("integer");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsibleRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentStepId");

                    b.HasIndex("ProsessId", "OrderIndex");

                    b.ToTable("ProsessSteps");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProsessId", "Name")
                        .IsUnique();

                    b.ToTable("ProsessTags");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeLog")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GitCommitHash")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GitTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublishedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("ProsessId", "IsCurrent");

                    b.HasIndex("ProsessId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ProsessVersions");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 26, 20, 7, 49, 193, DateTimeKind.Utc).AddTicks(3300),
                            Description = "Systemadministrator med full tilgang",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 26, 20, 7, 49, 193, DateTimeKind.Utc).AddTicks(3670),
                            Description = "Eier av prosesser, kan redigere og godkjenne",
                            Name = "ProsessEier"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 26, 20, 7, 49, 193, DateTimeKind.Utc).AddTicks(3670),
                            Description = "Kvalitetssikring, kan godkjenne endringer",
                            Name = "QA"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 26, 20, 7, 49, 193, DateTimeKind.Utc).AddTicks(3670),
                            Description = "Fagekspert, kan foreslå endringer",
                            Name = "SME"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 26, 20, 7, 49, 193, DateTimeKind.Utc).AddTicks(3670),
                            Description = "Vanlig bruker, kun lesetilgang",
                            Name = "Bruker"
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.StepConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FromStepId")
                        .HasColumnType("integer");

                    b.Property<int>("ToStepId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromStepId");

                    b.HasIndex("ToStepId");

                    b.ToTable("StepConnections");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 23, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@prosessportal.no",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$N8gNZ4Hg/JQXS4PZH6YX6e3rR5Zf6KjV8W5Qf2S4h3G6Yq9Pb7Ed",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            AssignedAt = new DateTime(2025, 11, 23, 17, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Actor", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ActorNote", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Actor", "Actor")
                        .WithMany("Notes")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ActorRole", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Actor", "Actor")
                        .WithMany("ActorRoles")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Prosess", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProsessPortal.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DeletedByUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessApprovalComment", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.ProsessApprovalRequest", "ApprovalRequest")
                        .WithMany("Comments")
                        .HasForeignKey("ApprovalRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovalRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessApprovalHistory", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany()
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prosess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessApprovalRequest", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany()
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Prosess");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessAutoSave", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany()
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prosess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessDeletionHistory", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany()
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prosess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessEditConflict", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany()
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProsessPortal.Core.Entities.User", "User1")
                        .WithMany()
                        .HasForeignKey("UserId1")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "User2")
                        .WithMany()
                        .HasForeignKey("UserId2")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prosess");

                    b.Navigation("ResolvedByUser");

                    b.Navigation("User1");

                    b.Navigation("User2");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessEditSession", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.ProsessVersion", "CreatedVersion")
                        .WithMany()
                        .HasForeignKey("CreatedVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany()
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedVersion");

                    b.Navigation("Prosess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessStep", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.ProsessStep", "ParentStep")
                        .WithMany("SubSteps")
                        .HasForeignKey("ParentStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany("Steps")
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentStep");

                    b.Navigation("Prosess");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessTag", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany("Tags")
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prosess");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessVersion", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany("Versions")
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Prosess");

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.StepConnection", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.ProsessStep", "FromStep")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("FromStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.ProsessStep", "ToStep")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("ToStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStep");

                    b.Navigation("ToStep");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.UserRole", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Actor", b =>
                {
                    b.Navigation("ActorRoles");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Prosess", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessApprovalRequest", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessStep", b =>
                {
                    b.Navigation("IncomingConnections");

                    b.Navigation("OutgoingConnections");

                    b.Navigation("SubSteps");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
