// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProsessPortal.Infrastructure.Data;

#nullable disable

namespace ProsessPortal.Infrastructure.Migrations
{
    [DbContext(typeof(ProsessPortalDbContext))]
    [Migration("20251123213655_InitialCreateWithCorrectStepTypes")]
    partial class InitialCreateWithCorrectStepTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProsessPortal.Core.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Resource", "Action")
                        .IsUnique();

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "view",
                            Description = "Se prosesser",
                            Name = "view_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 2,
                            Action = "create",
                            Description = "Opprette prosesser",
                            Name = "create_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 3,
                            Action = "edit",
                            Description = "Redigere prosesser",
                            Name = "edit_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 4,
                            Action = "delete",
                            Description = "Slette prosesser",
                            Name = "delete_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 5,
                            Action = "approve",
                            Description = "Godkjenne prosesser",
                            Name = "approve_prosess",
                            Resource = "prosess"
                        },
                        new
                        {
                            Id = 6,
                            Action = "view",
                            Description = "Se QA-kø",
                            Name = "view_qa_queue",
                            Resource = "qa"
                        },
                        new
                        {
                            Id = 7,
                            Action = "approve",
                            Description = "Godkjenne endringer",
                            Name = "approve_changes",
                            Resource = "qa"
                        },
                        new
                        {
                            Id = 8,
                            Action = "reject",
                            Description = "Avvise endringer",
                            Name = "reject_changes",
                            Resource = "qa"
                        },
                        new
                        {
                            Id = 9,
                            Action = "manage",
                            Description = "Administrere brukere",
                            Name = "manage_users",
                            Resource = "user"
                        },
                        new
                        {
                            Id = 10,
                            Action = "manage",
                            Description = "Administrere roller",
                            Name = "manage_roles",
                            Resource = "role"
                        },
                        new
                        {
                            Id = 11,
                            Action = "view",
                            Description = "Se audit-logg",
                            Name = "view_audit_log",
                            Resource = "audit"
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Prosess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GitBranch")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("GitPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("GitRepository")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Status");

                    b.HasIndex("Title");

                    b.ToTable("Prosesser");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "HR",
                            CreatedAt = new DateTime(2025, 10, 24, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Komplett prosess for å ta imot nye medarbeidere",
                            GitBranch = "main",
                            IsActive = true,
                            Status = 3,
                            Title = "Ny medarbeider onboarding",
                            UpdatedAt = new DateTime(2025, 11, 18, 17, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 25
                        },
                        new
                        {
                            Id = 2,
                            Category = "IT",
                            CreatedAt = new DateTime(2025, 10, 9, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Prosess for bestilling av nytt IT-utstyr til medarbeidere",
                            GitBranch = "main",
                            IsActive = true,
                            Status = 3,
                            Title = "IT-utstyr bestilling",
                            UpdatedAt = new DateTime(2025, 11, 13, 17, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 18
                        },
                        new
                        {
                            Id = 3,
                            Category = "Økonomi",
                            CreatedAt = new DateTime(2025, 11, 3, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Standard prosess for håndtering og godkjenning av fakturaer",
                            GitBranch = "main",
                            IsActive = true,
                            Status = 3,
                            Title = "Fakturahåndtering",
                            UpdatedAt = new DateTime(2025, 11, 21, 17, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 42
                        },
                        new
                        {
                            Id = 4,
                            Category = "Kundeservice",
                            CreatedAt = new DateTime(2025, 11, 16, 17, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Håndtering av kundehenvendelser i support-system",
                            GitBranch = "main",
                            IsActive = true,
                            Status = 1,
                            Title = "Kundehenvendelser support",
                            UpdatedAt = new DateTime(2025, 11, 22, 17, 0, 0, 0, DateTimeKind.Utc),
                            ViewCount = 8
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DetailedInstructions")
                        .HasColumnType("text");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentStepId")
                        .HasColumnType("integer");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<string>("ResponsibleRole")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentStepId");

                    b.HasIndex("ProsessId", "OrderIndex");

                    b.ToTable("ProsessSteps");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProsessId", "Name")
                        .IsUnique();

                    b.ToTable("ProsessTags");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeLog")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("GitCommitHash")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("GitTag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<int>("ProsessId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PublishedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("VersionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("PublishedByUserId");

                    b.HasIndex("ProsessId", "IsCurrent");

                    b.HasIndex("ProsessId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ProsessVersions");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 23, 21, 36, 55, 275, DateTimeKind.Utc).AddTicks(3980),
                            Description = "Systemadministrator med full tilgang",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 23, 21, 36, 55, 275, DateTimeKind.Utc).AddTicks(4300),
                            Description = "Eier av prosesser, kan redigere og godkjenne",
                            Name = "ProsessEier"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 23, 21, 36, 55, 275, DateTimeKind.Utc).AddTicks(4300),
                            Description = "Kvalitetssikring, kan godkjenne endringer",
                            Name = "QA"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 23, 21, 36, 55, 275, DateTimeKind.Utc).AddTicks(4300),
                            Description = "Fagekspert, kan foreslå endringer",
                            Name = "SME"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 23, 21, 36, 55, 275, DateTimeKind.Utc).AddTicks(4300),
                            Description = "Vanlig bruker, kun lesetilgang",
                            Name = "Bruker"
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 7
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.StepConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Condition")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FromStepId")
                        .HasColumnType("integer");

                    b.Property<int>("ToStepId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromStepId");

                    b.HasIndex("ToStepId");

                    b.ToTable("StepConnections");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 23, 17, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@prosessportal.no",
                            FirstName = "System",
                            IsActive = true,
                            LastName = "Administrator",
                            PasswordHash = "$2a$11$N8gNZ4Hg/JQXS4PZH6YX6e3rR5Zf6KjV8W5Qf2S4h3G6Yq9Pb7Ed",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssignedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            AssignedAt = new DateTime(2025, 11, 23, 17, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Prosess", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessStep", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.ProsessStep", "ParentStep")
                        .WithMany("SubSteps")
                        .HasForeignKey("ParentStepId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany("Steps")
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentStep");

                    b.Navigation("Prosess");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessTag", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany("Tags")
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prosess");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessVersion", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.Prosess", "Prosess")
                        .WithMany("Versions")
                        .HasForeignKey("ProsessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "PublishedByUser")
                        .WithMany()
                        .HasForeignKey("PublishedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("Prosess");

                    b.Navigation("PublishedByUser");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.StepConnection", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.ProsessStep", "FromStep")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("FromStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.ProsessStep", "ToStep")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("ToStepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStep");

                    b.Navigation("ToStep");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.UserRole", b =>
                {
                    b.HasOne("ProsessPortal.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProsessPortal.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Prosess", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("Tags");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.ProsessStep", b =>
                {
                    b.Navigation("IncomingConnections");

                    b.Navigation("OutgoingConnections");

                    b.Navigation("SubSteps");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("ProsessPortal.Core.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
